version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.aws:/root/.aws  # Mount local AWS credentials
    ports:
      - "8501:8501"
    env_file:
      - .env